export const quotes = [
  { quote: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { quote: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
  { quote: "Do something today that your future self will thank you for.", author: "Unknown" },
  { quote: "You don't have to be perfect to be amazing.", author: "Unknown" },
  { quote: "Success is not about being better than someone else, it's about being better than you were yesterday.", author: "Unknown" },
  { quote: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { quote: "You are stronger than you seem, braver than you believe, and smarter than you think.", author: "A.A. Milne" },
  { quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { quote: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr." },
  { quote: "You don't have to control your thoughts. You just have to stop letting them control you.", author: "Dan Millman" },
  { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { quote: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { quote: "You are not a victim, you are a volunteer.", author: "Unknown" },
  { quote: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama XIV" },
  { quote: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
  { quote: "You can't start the next chapter of your life if you keep re-reading the last one.", author: "Unknown" },
  { quote: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
  { quote: "You can't go back and change the beginning, but you can start where you are and change the ending.", author: "C.S. Lewis" },
  { quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { quote: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
  { quote: "You get in life what you have the courage to ask for.", author: "Oprah Winfrey" },
  { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
  { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { quote: "You can't hit a target you can't see.", author: "Zig Ziglar" },
  { quote: "I don't count my sit-ups. I only start counting when it starts burning.", author: "Muhammad Ali" },
  { quote: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
  { quote: "Don't be afraid to give up the good to go for the great.", author: "John D Rockefeller" }
]