export const quotes = [
  { quote: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { quote: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
  { quote: "Do something today that your future self will thank you for.", author: "Unknown" },
  { quote: "You don't have to be perfect to be amazing.", author: "Unknown" },
  { quote: "Success is not about being better than someone else, it's about being better than you were yesterday.", author: "Unknown" },
  { quote: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { quote: "You are stronger than you seem, braver than you believe, and smarter than you think.", author: "A.A. Milne" },
  { quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { quote: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr." },
  { quote: "You don't have to control your thoughts. You just have to stop letting them control you.", author: "Dan Millman" },
  { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { quote: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { quote: "You are not a victim, you are a volunteer.", author: "Unknown" },
  { quote: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama XIV" },
  { quote: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
  { quote: "You can't start the next chapter of your life if you keep re-reading the last one.", author: "Unknown" },
  { quote: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
  { quote: "You can't go back and change the beginning, but you can start where you are and change the ending.", author: "C.S. Lewis" },
  { quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { quote: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
  { quote: "You get in life what you have the courage to ask for.", author: "Oprah Winfrey" },
  { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
  { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { quote: "You can't hit a target you can't see.", author: "Zig Ziglar" },
  { quote: "I don't count my sit-ups. I only start counting when it starts burning.", author: "Muhammad Ali" },
  { quote: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
  { quote: "Don't be afraid to give up the good to go for the great.", author: "John D Rockefeller" },
  { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { quote: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
  { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { quote: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
  { quote: "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.", author: "Jamie Paolinetti" },
  { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { quote: "Do the hard jobs first. The easy jobs will take care of themselves.", author: "Dale Carnegie" },
  { quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
  { quote: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { quote: "Courage is one step ahead of fear.", author: "Coleman Young" },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { quote: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy" },
  { quote: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { quote: "Don’t stop when you’re tired. Stop when you’re done.", author: "Unknown" },
  { quote: "Small steps in the right direction can turn out to be the biggest step of your life.", author: "Unknown" },
  { quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { quote: "You don't need to be the fastest; just don't stop.", author: "Unknown" },
  { quote: "Focus on the step in front of you, not the whole staircase.", author: "Unknown" },
  { quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { quote: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
  { quote: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
  { quote: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { quote: "A champion is someone who gets up when they can’t.", author: "Jack Dempsey" },
  { quote: "Great things never come from comfort zones.", author: "Unknown" },
  { quote: "Don’t limit your challenges. Challenge your limits.", author: "Unknown" },
  { quote: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { quote: "Success doesn’t come to you. You go to it.", author: "Marva Collins" },
  { quote: "Work hard in silence, let success be your noise.", author: "Frank Ocean" },
  { quote: "Your potential is endless. Go do what you were created to do.", author: "Unknown" },
  { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
  { quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
  { quote: "If it doesn’t challenge you, it doesn’t change you.", author: "Fred DeVito" },
  { quote: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
  { quote: "Don’t downgrade your dream just to fit your reality. Upgrade your conviction to match your destiny.", author: "Unknown" },
  { quote: "It’s never too late to be what you might have been.", author: "George Eliot" },
  { quote: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
  { quote: "No pressure, no diamonds.", author: "Thomas Carlyle" },
  { quote: "Hustle in silence and let your success make the noise.", author: "Unknown" },
  { quote: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { quote: "Take the risk or lose the chance.", author: "Unknown" },
  { quote: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { quote: "Dream it. Wish it. Do it.", author: "Unknown" },
  { quote: "Never bend your head. Always hold it high. Look the world straight in the eye.", author: "Helen Keller" },
  { quote: "If you’re not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { quote: "You can’t build a reputation on what you are going to do.", author: "Henry Ford" },
  { quote: "Don’t quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali" },
  { quote: "Great things are done by a series of small things brought together.", author: "Vincent Van Gogh" },
  { quote: "The best view comes after the hardest climb.", author: "Unknown" },
  { quote: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong" },
  { quote: "You can’t cross the sea merely by standing and staring at the water.", author: "Rabindranath Tagore" },
  { quote: "Dream as if you’ll live forever, live as if you’ll die today.", author: "James Dean" },
  { quote: "Believe in your infinite potential. Your only limitations are those you set upon yourself.", author: "Roy T. Bennett" },
  { quote: "Don’t let the fear of losing be greater than the excitement of winning.", author: "Robert Kiyosaki" },
  { quote: "You were born to be real, not perfect.", author: "Unknown" },
  { quote: "Your passion is waiting for your courage to catch up.", author: "Isabelle Lafleche" },
  { quote: "Stop being afraid of what could go wrong and start being excited about what could go right.", author: "Tony Robbins" },
  { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { quote: "If you believe it will work out, you’ll see opportunities. If you don’t believe it will work out, you’ll see obstacles.", author: "Wayne Dyer" },
  { quote: "Success is the ability to go from one failure to another with no loss of enthusiasm.", author: "Winston Churchill" },
  { quote: "Don’t stop until you’re proud.", author: "Unknown" }
]